/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewcontroller;

import java.awt.CardLayout;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import model.entities.Clinic;
import model.entities.Owner;
import model.entities.Pet;

/**
 *
 * @author Thomas Barr-Taylor
 */
public class MainFrame extends javax.swing.JFrame {
    Clinic clinic;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        clinic = new Clinic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTaskBar = new javax.swing.JPanel();
        btnPets = new javax.swing.JButton();
        btnOwners = new javax.swing.JButton();
        panelLeft = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        panelPetInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboPetType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboOwner = new javax.swing.JComboBox<>();
        btnAddPet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePets = new javax.swing.JTable();
        panelOwnerInfo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        btnAddPet1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOwners = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                onWindowOpened(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pet Clinic");
        panelTitle.add(jLabel1);

        getContentPane().add(panelTitle, java.awt.BorderLayout.PAGE_START);

        panelTaskBar.setBackground(new java.awt.Color(0, 102, 102));

        btnPets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPets.setText("Pets");
        btnPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetsActionPerformed(evt);
            }
        });
        panelTaskBar.add(btnPets);

        btnOwners.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOwners.setText("Owners");
        btnOwners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnersActionPerformed(evt);
            }
        });
        panelTaskBar.add(btnOwners);

        getContentPane().add(panelTaskBar, java.awt.BorderLayout.PAGE_END);

        panelLeft.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        getContentPane().add(panelLeft, java.awt.BorderLayout.LINE_START);

        panelRight.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        getContentPane().add(panelRight, java.awt.BorderLayout.LINE_END);

        panelMain.setBackground(new java.awt.Color(0, 153, 153));
        panelMain.setLayout(new java.awt.CardLayout());

        panelPetInfo.setBackground(new java.awt.Color(0, 102, 0));
        panelPetInfo.setLayout(new javax.swing.BoxLayout(panelPetInfo, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Pet Info");
        jPanel1.add(jLabel3);

        panelPetInfo.add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Pet Name");
        jPanel3.add(jLabel4);

        txtPetName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPetName.setText("Rover");
        jPanel3.add(txtPetName);

        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Pet Type");
        jPanel3.add(jLabel7);

        comboPetType.setEditable(true);
        comboPetType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboPetType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dog ", "Cat", "Hamster", "Guinea Pig", "Parrot", "Other", " " }));
        jPanel3.add(comboPetType);

        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Owner");
        jPanel3.add(jLabel2);

        comboOwner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboOwner);

        btnAddPet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddPet.setText("Add Pet");
        btnAddPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPetActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddPet);

        panelPetInfo.add(jPanel3);

        tablePets.setBackground(new java.awt.Color(0, 102, 102));
        tablePets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Type", "Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePets);

        panelPetInfo.add(jScrollPane2);

        panelMain.add(panelPetInfo, "cardPet");

        panelOwnerInfo.setBackground(new java.awt.Color(0, 102, 0));
        panelOwnerInfo.setLayout(new javax.swing.BoxLayout(panelOwnerInfo, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout2.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Owner Info");
        jPanel5.add(jLabel5);

        panelOwnerInfo.add(jPanel5);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(408, 60));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Owner Name");
        jPanel2.add(jLabel6);

        txtOwnerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOwnerName.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel2.add(txtOwnerName);

        btnAddPet1.setText("Add Owner");
        btnAddPet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOwnerActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddPet1);

        panelOwnerInfo.add(jPanel2);
        panelOwnerInfo.add(jSeparator1);

        jScrollPane3.setBackground(new java.awt.Color(0, 51, 51));

        tableOwners.setBackground(new java.awt.Color(0, 102, 102));
        tableOwners.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableOwners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableOwners);

        panelOwnerInfo.add(jScrollPane3);

        panelMain.add(panelOwnerInfo, "cardOwner");

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * this function will display the pets panel
     * @param evt button near bottom called btnPets
     */
    private void btnPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetsActionPerformed
      CardLayout layout =(CardLayout) panelMain.getLayout();
      layout.show(panelMain, "cardPet");
    }//GEN-LAST:event_btnPetsActionPerformed
    
    /**
     * this function will display the owners panel
     * @param evt button near bottom called btnOwners
     */
    private void btnOwnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnersActionPerformed
      CardLayout layout =(CardLayout) panelMain.getLayout();
      layout.show(panelMain, "cardOwner");
    }//GEN-LAST:event_btnOwnersActionPerformed
    
    /**
     * once you start the program this function is called and it calls 
     * functions that will populate the tables and comboBox
     * @param evt 
     */
    private void onWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowOpened
        // TODO add your handling code here:        
        updatePetTable();
        updateOwnersList();
        updateOwnersTable();
    }//GEN-LAST:event_onWindowOpened
    /**
     * this function will be used to populate the pets table with the pet's id,
     * name, type, and Owner as well as modify the table columns size
     */
    private void updatePetTable() {
        String[] columnNames = new String[] {"id","Name","Type","Owner"};
        int columnCount = columnNames.length;

        String[][] data = clinic.getPetArray(columnCount);
       
        DefaultTableModel model = new DefaultTableModel(data,columnNames);
        tablePets.setModel(model);
        
        TableColumnModel columnModel = tablePets.getColumnModel();
        
        int width = panelPetInfo.getWidth();
        
        TableColumn column = columnModel.getColumn(0);
        column.setPreferredWidth(width / 10);
        
        columnModel.getColumn(1).setPreferredWidth(2 * width / 10);
        columnModel.getColumn(2).setPreferredWidth(3 * width / 10);
        columnModel.getColumn(3).setPreferredWidth(4 * width / 10);
        updateOwnersTable();
    }
    /**
     * this function will populate the owners table with the owners id, name and
     * the owners pets
     */
    private void updateOwnersTable() {
        String[] columnNames = new String[] {"Id", "Name", "Owners pet(s)"};
        int columnCount = columnNames.length;
        
        String[][] data = clinic.getOwnerArray(columnCount);
        
        DefaultTableModel model = new DefaultTableModel(data,columnNames);
        tableOwners.setModel(model);
        updateOwnersList();
    }
    /**
     * populates the list of owner's name in the combo box
     */
    private void updateOwnersList(){
        List<Owner> ownerList = clinic.getOwnerList();
        comboOwner.removeAllItems();
        comboOwner.addItem(" - ");
        for(Owner owner : ownerList)
        {
            comboOwner.addItem(owner.getOwnerName());
        } 
    }
    /**
     * this function will try to add a pet from the data given in the text boxes
     * and combo boxes and put the data into 
     * @param evt 
     */
    private void btnAddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPetActionPerformed
        // TODO add your handling code here: 
        if (comboOwner.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "select a pet owner");
            return;
        }
        String ownerName = comboOwner.getSelectedItem().toString();
        try {
            Owner owner = clinic.findOwnerByName(ownerName);
            String petName = txtPetName.getText();
            String petType = comboPetType.getSelectedItem().toString();
            clinic.addPet(petName,petType,owner);
            JOptionPane.showMessageDialog(rootPane, owner.getPetCollection().toString());
            String petlist = "";
            for (Pet pet : owner.getPetCollection()) {
                petlist += pet.getPetName() + ", ";
            }
            JOptionPane.showMessageDialog(rootPane, petlist);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Could not add pet to database");
            return;
        }
        updatePetTable();
    }//GEN-LAST:event_btnAddPetActionPerformed

    private void btnAddOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOwnerActionPerformed
        // TODO add your handling code here:
        try {
            String ownerName = txtOwnerName.getText();
            clinic.addOwner(ownerName);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Could not add owner to database");
        }
        updateOwnersTable();
    }//GEN-LAST:event_btnAddOwnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPet;
    private javax.swing.JButton btnAddPet1;
    private javax.swing.JButton btnOwners;
    private javax.swing.JButton btnPets;
    private javax.swing.JComboBox<String> comboOwner;
    private javax.swing.JComboBox<String> comboPetType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelOwnerInfo;
    private javax.swing.JPanel panelPetInfo;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTaskBar;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTable tableOwners;
    private javax.swing.JTable tablePets;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtPetName;
    // End of variables declaration//GEN-END:variables

}
